### ISSUE TITLE
Unclear about units of packet-loss

### ISSUE THREAD

**Issue by childofsoong** [tylertreat/Comcast#15]
The README file indicates that `--packet-loss=0.1` corresponds to 10% packet loss, but then further down lists profiles that would seem to include 150% or 200% packet loss.  The code seems to indicate that 0.1 would actually mean 0.1%, not 10%.

**Comment by tylertreat** [comment]
It looks like there's actually a bug with the [ipfw backend](https://github.com/tylertreat/Comcast/blob/master/throttler/ipfw.go#L56). The packet loss value should be multiplied by 100 like it is in [tc](https://github.com/tylertreat/Comcast/blob/master/throttler/tc.go#L61) so that 0.1 would correspond to 10%.

**Comment by tylertreat** [comment]
Actually, I take that back. I think the code is correct. The profiles don't correspond correctly though.

**Comment by Term1nal** [comment]
since this is a simplification wrapper, would it not be better to change the command line flag to be a bit easier to understand, and just math the output to the wrapped system (tc or ipfw) to be the proper value?

like say --packet-loss=10% would get translated to 0.1 for ipfw

Would that not make it a bit easier to grasp? Should be pretty easy to modify while I'm overhauling the wrappers.

**Comment by childofsoong** [comment]
I think that would be the best option, personally.  That way, regardless of backend, the user can be explicit about their desired settings.

**Comment by tylertreat** [comment]
Yeah, I agree.

**Comment by Term1nal** [comment]
#closeme
